name: Build macOS App with PyInstaller

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: 📦 Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller cryptography

      - name: 🏗️ Build macOS app
        run: |
          pyinstaller --windowed --name "SecureMessenger" secure_message_gui.py

      - name: 📤 Upload .app bundle
        uses: actions/upload-artifact@v4
        with:
          name: SecureMessenger-macOS-app
          path: dist/SecureMessenger.app
